### ISSUE TITLE
Missing CS form language list

### ISSUE THREAD

**Issue by michalss** [arturograu/country_flags#14]
HI im missing code cs, which is czech language code..

![image](https://github.com/arturograu/country_flags/assets/1000729/704dce7e-1ed1-4358-bf1e-a2fb44e49e42)

**Comment by michalss** [comment]
well i did try more its generally CountryFlag.fromLanguageCode does not work.. for example TR, CS, SK etc..

**Comment by michalss** [comment]
well not many language codes works.. :(

**Comment by arturograu** [comment]
Hello @michalss . Thank you for reporting the bug, I already added those missing languages and it will be available in pub.dev soon.

If you find more missing language codes don't hesitate and create a new issue.
