### ISSUE TITLE
How to show circular flag image?

### ISSUE THREAD

**Issue by KrishnendraPrakash** [arturograu/country_flags#20]
How to show circular flag image?
 As this `CountryFlag.fromCountryCode`  returns ClipRRect .

But image still showing in rectangle form .

Please make a use case where I can show flag image in circle.

**Comment by vietstone-ng** [comment]
Hi, this is my working code:
```
        SizedBox(
          width: 24,
          height: 24,
          child: ClipRRect(
            borderRadius: BorderRadius.circular(12),
            child: FittedBox(
              fit: BoxFit.cover,
              child: CountryFlag.fromLanguageCode(
                'fr',
              ),
            ),
          ),
        ),
```

**Comment by arturograu** [comment]
I added the ability to show the circular flag here https://github.com/arturograu/country_flags/pull/36.

To do it you can:
```dart
CountryFlag.fromCountryCode(
  'ES',
  shape: const Circle(),
);
```
