### ISSUE TITLE
Portuguese "pt" is missing from _flagCodesLanguages

### ISSUE THREAD

**Issue by adigladi** [arturograu/country_flags#33]
I noticed that Portuguese `pt` is missing from the `_flagCodesLanguages` list.

**Comment by adigladi** [comment]
Pull request up here to add it: https://github.com/arturograu/country_flags/pull/34

**Comment by arturograu** [comment]
Hello @adigladi , I added the fix here: https://github.com/arturograu/country_flags/pull/36

Thank you for reporting it!
