### ISSUE TITLE
Test widget

### ISSUE THREAD

**Issue by EliaTolin** [arturograu/country_flags#4]
Hi,

I would like insert this widget in my unit test.

How can I do? 

For example,
if I pass the parameter code "en" it show a blank flag,  it is correct because "en" is language code not country but I use your widget for show the flag of the languages.

Thanks.

**Comment by arturograu** [comment]
Hi @EliaTolin !

Let me check what I can do.

Best regards!

**Comment by arturograu** [comment]
Hi @EliaTolin you should be able to generate flags by language code with the new version.

Regards!
