### ISSUE TITLE
Support 3 char ISO codes

### ISSUE THREAD

**Issue by erzohaib** [arturograu/country_flags#42]
Currently it is accepting only 2 char ISO codes. It should also accept 3 char ISO codes as most of the time developers uses 3 char ISO codes in database for view and functionality purposes.

It is accepting following:
CountryFlag.fromCountryCode('US');

But not accepting
CountryFlag.fromCountryCode('USA');

**Comment by NilShiroya** [comment]
country_currency_pickers

I was facing the same issue so I used this package insted

**Comment by fransdhinta** [comment]
@erzohaib i have created PR https://github.com/arturograu/country_flags/pull/44 for this feature

**Comment by arturograu** [comment]
Fix from [PR #44](https://github.com/arturograu/country_flags/pull/44) released in [v3.1.0](https://github.com/arturograu/country_flags/releases/tag/v3.1.0)
