### ISSUE TITLE
CountryFlag.fromLanguageCode() showing '?' for Romanian language

### ISSUE THREAD

**Issue by Dark-Schneider-666** [arturograu/country_flags#43]
Just call with CountryFlag.fromLanguageCode('ro') for testing purposes.

Nice package BTW ;)

**Comment by arturograu** [comment]
Thank you @Dark-Schneider-666 !
The issue should be fixed by the PR #41 in the release [v3.1.0](https://github.com/arturograu/country_flags/releases/tag/v3.1.0)
