### ISSUE TITLE
edit Syrian falg

### ISSUE THREAD

**Issue by mohamadAdibTawil** [arturograu/country_flags#50]
from 5 days Syrian flag change to other flag 
this is the new flag 
please kindly change the flag
![syrian-opposition-flag](https://github.com/user-attachments/assets/99d2f4b1-9631-4489-a3c5-e670968d37d0)

**Comment by mohamadAdibTawil** [comment]
thank you very much sir 
but i have question 
i updated the package but it still show previous flag 
what must i do for show new flag ?

**Comment by arturograu** [comment]
> thank you very much sir but i have question i updated the package but it still show previous flag what must i do for show new flag ?

Hi @mohamadAdibTawil , you should be able to see the new flag if you update to the 3.2.0. I just pushed it to pub.dev.

**Comment by mohamadAdibTawil** [comment]
thanks a lot 🤍
